feat slackを用いたデプロイ承認フロー構築記事
kazuya0523/zenn pull request #1
Opened 2024-06-17 05:58 UTC by kazuya0523

2024-06-17 08:16 UTC, gizm000 reviewed
うーーん、これは全体構成を変えた方が良いと感じました 💦 
開発フローの話をしたいのか、GitHub EnterpriseをSlackカスタムファンクションで回避したいのか
、Docker image共通化の話をしたいのか、はたまた全部を話したいのか？？？
混ざり合いながら各所が片手落ち、みたいになっている気がしています...

Slackカスタムファンクションの話でも「ステージングと本番環境がー」とか「QAがー」といった関係ないものが混ざっていて、肝心のSlackカスタムファンクションの話が省略されてしまっています 😓 

おそらく以下の話の流れにしたいのですよね？？
・開発フローを見直した
　・デプロイ承認制にしたい
　　・けどGitHubEnterpriseが高いから契約したくない
　・Docker imageを環境ごとに分けたくない

ふわっと開発フローの話が出つつ、「デプロイ承認制にしたい」個別の話になった瞬間にフローの話があるようなないような。Slackカスタムファンクションもあるようなないような・・・

最後に関係ない部分も大量に含まれた謎フローがドンと出されて終わる。

みたいな構成になっています 🤔 

とりうる対策としては、シンプルに2つ。
1. 記事を分ける
2. 大きめの記事を頑張って書く

記事を分けるのは簡単ですね！
- GitHub Enterpriseを利用しなくてもSlackカスタムファンクションでできるんやでっていうだけの記事 
- Dockerイメージが環境ごとに存在していたのをひとつに統一したという記事


大きめの記事を頑張って書くのであれば、主軸をフロー回収におかないといけないです。
全体のフロー、ステップごとに区切ったフロー。適切な粒度で説明していく必要があります 👀 
これをいい記事に仕上げるのは難易度高いと思います・・・！

ということで、記事を分割でいきましょう... 🙏

2024-06-25 05:03 UTC, kazuya0523 commented
@gizm000 
修正しました。。！👀
お手の際に再レビューお願いいたします 🙇

2024-07-04 08:02 UTC, gizm000 requested changes
全体像が全部文章ベースなので、最初に離脱してしまう印象があります 💦 

「どのように実現するか？」の項目で、以下のように構造がわかりやすい表現にしたいですね... 🤔 

あとはインラインでコメント書いた部分の修正で大丈夫です 🙏 

```
🍳 用意するもの
GitHub Actions
・開発環境へのデプロイ
・ステージング環境へのデプロイ
・本番環境へのデプロイ

Slackチャンネル
・開発環境
・ステージング環境
・本番環境

🚀 フローの概要
1. GHA   : 開発環境へデプロイ
2. Slack : 開発環境チャンネルにデプロイ完了通知
           開発環境チャンネルにQA完了ボタンを表示
4. QA完了✨ 
5. Slack : 開発環境チャンネルのQA完了ボタンを押下
6. Slack : ステージング/本番チャンネルに[デプロイ]ボタンを表示
7. Slack : [デプロイ]ボタンを押下
8. GHA   : ステージング/本番へデプロイ
```

2024-07-05 00:36 UTC, kazuya0523 commented
お忙しい中レビューありがとうございました🙇
全体像は文章ベースではなく箇条書きにするだけでかなり見通しがよくなりますね💦
絵文字を適宜使うのも重要ですね。。！

勉強になりました！
今後、文章力あげられるように頑張っていきます！

2024-07-10 02:55 UTC, gizm000 approved these changes
記念すべき初回記事 👀

2024-07-10 02:58 UTC, merged